### ISSUE TITLE
Formula used to calculate Kc

### ISSUE THREAD

**Issue by wittregr** [VlachosGroup/openmkm#30]
Please provide the formula used to calculate Kc under the kc.out documentation and and include the units Kc will have for each formula.

**Comment by wittregr** [comment]
Kc should be calculated from Kp with a unit adjustment (1/RT) for the difference in gas moles on the two sides of the equation. Kp should be calculated from Standard Gibb's free energy. That is at 1 bar. NASA polynomials are at 1 bar so they can be used without adding any pressure dependence. In Sform you show a pressure dependence. Did you then use that Sform to calculate Srxn and subsequently Grxn. Then did you use that Grxn or the standard Grxn to calculate Kp?

**Comment by jonlym** [comment]
_Not meant as a reply to Gerhard. Just referencing previous discussions._
Previously established that Hform and Sform were calculated at the inlet pressure in issue #18

**Comment by MaxRCohen** [comment]
Hi @mbkumar, looks like we still need this information. I know the pressure dependence of Kc is something currently being reviewed, so it makes sense this is not updated yet. Just a note for when the review is complete: could you please the formulas for Kc where the documentation says "1.  Adsorption reaction:" and "2. Surface reaction:"?

**Comment by mbkumar** [comment]
Sure will do. I need to make sure I get things right on this.

**Comment by skasiraj** [comment]
In the file kc.out, OpenMKM prints "concentration units" equilibrium constants i.e., Kc for all reactions at reference pressure (depends on the reference pressure set in the thermo.xml file, typically 1 bar). 

**Summary**: Kc calculations are done in Cantera. In Cantera Kp and there Kc are obtained from the reference state chemical-potentials. Since we are using ideal gas assumption (for gas phase) and ideal solution assumption (for surface phases), the reference state chemical potentials are equivalent and can be directly obtained from pure species enthalpy and entropy and is independent of pressure. @MaxRCohen and @wittregr if this explanation is good enough, we could perhaps update the documentation and close this issue. 

**Details**
- The actual estimation of the Kc values is implemented in the Cantera library and obtained using the function `getEquilibriumConstants()` [code](https://cantera.org/documentation/docs-2.5/doxygen/html/d4/dc4/classCantera_1_1Kinetics.html#a0115ce55d0098842313132275e343c33). This function initially defined in the Kinetics.h header file, is (re)-implemented independently for [GasKinetics](https://cantera.org/documentation/docs-2.5/doxygen/html/d3/d0b/GasKinetics_8cpp_source.html#l00111) and [InterfaceKinetics](https://cantera.org/documentation/docs-2.5/doxygen/html/d3/db3/InterfaceKinetics_8cpp_source.html#l00170)
- Although, it is not very obvious what is the state of Gibbs free energy (is it at reference state, is it independent of P etc.) used here and what the log standard concentration term is, it becomes more obvious from the thermodynamic definitions of the phase itself. 
- Look at the sections *Application within Kinetics managers* and the preceding sections at [IdealGasPhaseThermo](https://cantera.org/documentation/docs-2.5/doxygen/html/d7/dfa/classCantera_1_1IdealGasPhase.html#details) to understand the states of gibbs-freeenergy/chem potential and the method of calculation of equilibrium constant. Similar treatise is also applied to the Surface reactions where the species are assumed in an ideal solution. 
- See a snapshot from the documentation below

![image](https://user-images.githubusercontent.com/22058505/138004344-e5177194-4b8f-47fa-8ff7-1f835fc86723.png)

![image](https://user-images.githubusercontent.com/22058505/138004517-ec06c3f0-4b12-4fd0-ad35-b09e4d32f8a4.png)
